### ISSUE TITLE
[bug] [ERR_MODULE_NOT_FOUND]: Cannot find module 'yargs-factory.js' imported from index.mjs

### ISSUE THREAD

**Issue by dasAtRagedy** [yargs/yargs#2352]
### Description

Using code snippet behaves differently between minor versions `17.7.2` and `17.7.1`
It compiles without any problems, however when I run with node, the error appears

### Background
I am using:
- node v18.17.0
- yargs 17.7.2
- typescript 5.1.6
- pnpm 8.6.7

### Code snippet
```ts
// more imports here
import yargs from "yargs";
import isValidFilename from "valid-filename";

function validateFileName(fileName: string) {
  if(!isValidFilename(fileName)){
    throw new Error(`Not a valid file name: ${fileName}`);
  }
}

const argv = yargs(process.argv.slice(2)).options({
  inputFileName: {
    description: "Input file name",
    alias: "i",
    type: "string",
    default: "in.json",
  },
  outputFileName: {
    description: "Output file name",
    alias: "o",
    type: "string",
    default: "out.json",
  },
}).parseSync();

validateFileName(argv.inputFileName);
validateFileName(argv.outputFileName);

const pathToInput = path.join(path.dirname(url.fileURLToPath(import.meta.url)), argv.inputFileName);
const pathToOutput = path.join(path.dirname(url.fileURLToPath(import.meta.url)), argv.outputFileName);
```

### Error message
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'project/node_modules/.pnpm/yargs@17.7.2/node_modules/yargs/build/lib/yargs-factory.js' imported from project/node_modules/.pnpm/yargs@17.7.2/node_modules/yargs/index.mjs
```

### Current resolution
Using older version- 17.7.1

**Comment by shadowspawn** [comment]
That is a tricky one! Almost nothing changed between 17.7.1 and 17.7.2, and I don't think the error is related to the code as such. I suspect TypeScript configuration settings are involved somehow.

Do you have a public project that I can try reproducing the error?

Something simple you could try is changing the import from `"yargs"` to `"yargs/yargs"`. This avoids some problems with TypeScript and targeting esm. The failure you observe does not match the known issues, so this is just a try-something suggestion and not a likely solution.

**Comment by shadowspawn** [comment]
If it is easy, do you still see the failure with Yargs v17.7.2 if you install the modules using `npm` rather than `pnpm`?

**Comment by dasAtRagedy** [comment]
The problem is with `const args = ...` specifically, when replaced with a string array it works; 
the same line in `.js` file is unmodified at all, and the issue was not during `tsc`, rather `node`;
changing to yargs/yargs did not help;
it's not exactly easy to install the modules with npm;
doesn't work on node 20.4.0 either

**Comment by dasAtRagedy** [comment]
slight update that I didn't notice:
when changing import to yargs/yargs, error changes to `Cannot find module '.../index.cjs' imported from .../yargs.mjs

**Comment by shadowspawn** [comment]
> The problem is with `const args = ...` specifically, when replaced with a string array it works; 

I don't see anything matching that in your example program, what does this refer to?

**Comment by dasAtRagedy** [comment]
my bad, `argv`,:
```javascript
const argv = yargs(process.argv.slice(2)).options({
  inputFileName: {
    description: "Input file name",
    alias: "i",
    type: "string",
    default: "in.json",
  },
  outputFileName: {
    description: "Output file name",
    alias: "o",
    type: "string",
    default: "out.json",
  },
}).parseSync();
```

**Comment by shadowspawn** [comment]
Did you sort this out @dasAtRagedy ?

If still broken, could you post your `tsconfig.json`?

**Comment by dasAtRagedy** [comment]
no, I did not, my solution was leaving it on a lower minor version.
I no longer have access to that piece of the codebase, I don't think I will be able to contribute to this issue much more than I have.

**Comment by shadowspawn** [comment]
(Thanks @dasAtRagedy)

**Comment by shadowspawn** [comment]
Thanks for the detailed report.

This issue has not come up again in 3 months, and no further information available. 

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you for your contributions.
