### ISSUE TITLE
Deno: Property argv does not exist on type YargsInstance

### ISSUE THREAD

**Issue by seanaye** [yargs/yargs#2035]
I have copied the example deno usage into a file but it will not compile due to error `Property argv does not exist on type YargsInstance`

I am using Deno version: 1.12.2

Code from readme (more or less)

```ts
import yargs from 'https://deno.land/x/yargs/deno.ts'
import { Arguments } from 'https://deno.land/x/yargs/deno-types.ts'

const input = yargs(Deno.args)
  .command('download <files...>', 'download a list of files', (yargs: any) => {
    return yargs.positional('files', {
      describe: 'a list of files to do something with'
    })
  }, (argv: Arguments) => {
    console.info(argv)
  })
  .strictCommands()
  .demandCommand(1)

console.log(input.argv)
```

**Comment by bcoe** [comment]
@seanaye we removed the `.argv` property accessor from `Deno` and ESM versions of yargs, I've confirmed that the following works on deno@1.14.1:

```js
import yargs from 'https://deno.land/x/yargs/deno.ts'
import { Arguments } from 'https://deno.land/x/yargs/deno-types.ts'

const input = yargs(Deno.args)
  .command('download <files...>', 'download a list of files', (yargs: any) => {
    return yargs.positional('files', {
      describe: 'a list of files to do something with'
    })
  }, (argv: Arguments) => {
    console.info(argv)
  })
  .strictCommands()
  .demandCommand(1)

console.log(input.parse())
```
