### PR TITLE
fix: expose helpers for legacy versions of Node.js

### LINKED ISSUE #1789: Readme CJS example fails with versions of Node older than 12.17
Using the CJS example code from the README.md seems to fail for me on all Node versions I tried before 12.17 (12.16.1, 12.15.0, 12.14.1 and 11.15.0):

```js
#!/usr/bin/env node
const yargs = require('yargs/yargs')
const { hideBin } = require('yargs/helpers')
const argv = yargs(hideBin(process.argv)).argv

if (argv.ships > 3 && argv.distance < 53.5) {
  console.log('Plunder more riffiwobbles!')
} else {
  console.log('Retreat from the xupptumblers!')
}
```

The error varies by version.

12.16.1:
```
Error: Cannot find module 'yargs/helpers'
```

12.14.1 and 12.15.0:
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: <snip>/yargs-node-error/node_modules/yargs/helpers.mjs
```

11.15.0:
```
Error: Cannot find module 'yargs/helpers'
```

Works fine in 12.17 and 12.18.

Here's a sample of how I set it up: https://github.com/gpoole/yargs-node-error

### PR DESCRIPTION
**Pull request by bcoe**
Expose helpers in extensionless `helpers` file, which older Node.js versions will interpret as a JavaScript file.

This is the only approach I have found to circumvent exceptions thrown when loading `.js` files when type is set to `module`.

Fixes #1789

### CODE REVIEW

**Comment by bcoe** [comment]
CC: @ljharb, @gpoole

File: helpers [hunk 1]
```diff
@@ -0,0 +1,15 @@
...
+  processArgv,
+} = require('./build/index.cjs');
+
+module.exports = {
+  applyExtends: (config, cwd, mergeExtends) => {
+    return applyExtends(config, cwd, mergeExtends, cjsPlatformShim);
+  },
+  hideBin: processArgv.hideBin,
+  Parser,
+};
```
Comment (ljharb) [inline helpers:15]: i'm confused, why an extensionless file instead of a `helpers` dir with a `package.json` that has `"type": "commonjs"` and an `index.js` file?

The current approach will be way more likely cause problems with parsers and resolvers (admittedly, ones with bugs, but i can't even confidently say `resolve` would work properly with this)

Comment (bcoe) [reply helpers:15]: I appreciate that having a subfolder would cleanup the top level a bit too, we could pull the mjs in there

**Comment by ljharb** [comment]
Does this fix #1799, or does it fix #1798?

**Comment by bcoe** [comment]
@ljharb Deno was type issues, which should be fixed on the main branch already... I might have to move away from TypeScript for Deno unless someone wants to submit and maintain types that work.
