### ISSUE TITLE
@types/typescript does not work with `import` syntax

### ISSUE THREAD

**Issue by dalcde** [yargs/yargs#1749]
Reproduce by running the following in an empty directory:
```sh
npm init
npm i yargs
echo "import yargs from 'yargs';" > index.ts
tsc index.ts
```

We get the error
```
index.ts:1:19 - error TS2307: Cannot find module 'yargs' or its corresponding type declarations.

1 import yargs from 'yargs'
                    ~~~~~~~


Found 1 error.
```
Reproduced with `yargs 16.0.3` and `tsc 4.0.2`.

**Comment by AviVahl** [comment]
https://github.com/yargs/yargs#typescript
yargs doesn't ship built-in types yet, so one has to install `@types/yargs` as well.

**Comment by dalcde** [comment]
This worked with yargs 15.4.2

**Comment by AviVahl** [comment]
Maintainers are working to convert the entire project to TypeScript: https://github.com/yargs/yargs/issues/1586
Work there is _probably_ related. They do write about `@types/yargs` and the built-in `.d.ts`

**Comment by bcoe** [comment]
I apologize for the confusion if created having this briefly work in v15. We do not intend to ship TypeScript definitions in yargs or yargs-parser in the near future.

Here's a [post on the topic](https://dev.to/bcoe/yargs-v16-released-14p7).

@types/yargs is well supported and used widely by the community, but.deviates sigificantly from the actual TypeScript API surface of the library.

**Comment by dalcde** [comment]
I understand that pure javascript libraries can be used in typescript projects (as in they can be imported and used, but not type checked), and I assumed that's how it previously worked. Currently it can't be imported at all.

**Comment by bcoe** [comment]
@dalcde the syntax should be:

```js
#!/usr/bin/env node
import yargs = require('yargs');

const argv = yargs.options({
  a: { type: 'boolean', default: false },
  b: { type: 'string', demandOption: true },
  c: { type: 'number', alias: 'chill' },
  d: { type: 'array' },
  e: { type: 'count' },
  f: { choices: ['1', '2', '3'] }
}).argv;
```

I believe to match the `@types/yargs` definitions.

**Comment by bcoe** [comment]
@dalcde I wonder if, now that we support ESM in yargs, there's a way `@types/yargs` could be  modified to support both `require` and `import` syntax.

The reason that `= require('yargs');`  is necessary, is  because the non-ESM API surface of yargs uses `module.exports`.

**Comment by AviVahl** [comment]
@bcoe you can already `import yargs as 'yargs';` if you have `esModuleInterop` turned on (default in `tsc --init`).
We do so in stylable: https://github.com/wix/stylable/blob/master/packages/cli/src/cli.ts

We are getting yargs in its `require` form though, as our modules transpile to commonjs (meaning a `require('yargs')` is being called).

**Comment by bcoe** [comment]
@AviVahl, I wish this was a bit more straightforward for folks ... especially now that the library itself does support ESM. I think there's just room  to improve the ESM/TypeScript interop story.

**Comment by bcoe** [comment]
@dalcde if @AviVahl's approach works for you, perhaps we can close this?

**Comment by dalcde** [comment]
I get the same error with --esModuleInterop

**Comment by bcoe** [comment]
@dalcde could you share a minimal repository that is having this issue?

**Comment by dalcde** [comment]
The commands at the OP of the issue creates such a repository.

**Comment by AviVahl** [comment]
Those commands do not include `@types/yargs`, so you'll get a type error.
Also, they do not include `npx tsc --init`, so no tsconfig.json was created, and you may be missing other important config (module/moduleResolution)

```
mkdir yargs-ts-test
cd yargs-ts-test/
npm init -y
npm i yargs
npm i @types/yargs typescript -D
npx tsc --init
echo "import yargs from 'yargs';" > index.ts
npx tsc index.ts 
```

Works just fine (notice the added `npm i @types/yargs typescript -D` and `npx tsc --init`).

**Comment by dalcde** [comment]
I can confirm that adding `@types/yargs` solves the problem. `tsc --init` does not.

The issue was that javascript libraries are normally usable with
typescript without typings, and that was the case with yargs prior to
16.0
