### ISSUE TITLE
demandOption doesn't work on v13.2.2

### ISSUE THREAD

**Issue by yuki-takei** [yargs/yargs#1315]
## How to reproduce?

1. Install v13.2.2
1. Write your code as in the example

    ```
    #!/usr/bin/env node
    var argv = require('yargs')
        .usage('Usage: $0 -w [num] -h [num]')
        .demandOption(['w','h'])
        .argv;
    ```

1. Invoke it without `h` option

    ```
    $ node ./area.js -w 1
    ```

## What happens?

```
TypeError: require(...).usage(...).demandOption is not a function
    at Object.<anonymous> (C:\Users\Yuki\dev\area.js:4:4)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

## What is the expected result?

- Show help with error message

**Comment by juergba** [comment]
I can't reproduce your error. I run your example and the output is fine:
```
D:\yargs>node ./issue_1315.js -w 1
Usage: issue_1315.js -w [num] -h [num]

Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]
  -w                                                                  [required]
  -h                                                                  [required]

Missing required argument: h
```
On Windows10, yargs v13.2.2
